"""Research inputs. Scores are analyst hypotheses, not measured market statistics."""
DATE = '2026-09-15'
FACTORS = ['Demand','Pain','WTP','Recurring','CAC','Retention','HighTicket','Competition','MVPEase','ROI','Morocco','Global','Moat','AI']
WEIGHTS = [10,10,10,10,10,10,7,5,5,5,5,5,5,3]
# ID order is permanent; ranking is computed independently.
RAW = '''
001|Receivables exception desk for industrial distributors|Accounts receivable|Morocco → Global|Morocco|Industrial distributors; 10–75 staff; 200+ credit invoices/month|Disputed invoices, missing delivery documents and broken payment promises delay cash|9,9,8,9,7,9,8,5,8,9,9,8,6,5|S01;S02;S06;S07;S08;S35;S36|Incumbents already handle disputes and exceptions; local workflow advantage must beat a configured incumbent. No WhatsApp dependency
002|HVAC maintenance proof-to-invoice|Field services|Morocco → Global|Morocco|Commercial HVAC contractors; 5–30 technicians; recurring service contracts|Completed jobs lack signed evidence and remain unbilled|8,8,8,10,7,9,7,6,7,9,9,8,7,4|S09;S10|Mobile adoption and strong localized field-service competition
003|Freight proof-of-delivery to invoice exceptions|Logistics and transport|Morocco → Global|Morocco|Road carriers; 10–75 vehicles; dispatcher plus billing clerk|Missing PODs prevent accepted invoices|8,9,8,9,7,9,8,6,6,9,8,8,7,6|S11;S12|TMS vendors already bundle POD and invoicing
004|Subcontractor variation approval and billing evidence|Construction|Global|UK|MEP subcontractors; 10–100 staff; 3+ simultaneous projects|Unapproved variations and weak evidence cause margin leakage|8,9,8,9,7,8,9,6,7,9,7,8,7,5|S13;S14|Contract-specific approval and adversarial buyer incentives
005|AI-assisted wholesale order intake|Wholesale order operations|Morocco → Global|Morocco|Industrial-parts wholesalers; 20–150 staff; 1000+ orders/month|Email and PDF orders rekeyed with SKU and unit errors|8,8,9,10,6,9,9,5,5,9,8,9,7,9|S15;S08|ERP integration and unit-of-measure errors; higher MVP cost
006|Evidence-linked tender response workspace|RFP and bid management|Global|France|Engineering/IT suppliers; 20–150 staff; 2+ bids/month|Repeated questionnaires consume senior staff time|8,8,8,8,6,8,9,5,7,8,7,9,6,9|S16;S17|AI drafting already common; irregular tender frequency
007|Agency scope and margin leakage monitor|Agency professional services|Global|UK|Retainer agencies; 10–50 staff; 15+ active retainers|Scope creep hides loss-making accounts|8,8,7,9,7,8,6,5,8,9,7,9,6,7|S18|Productive and Scoro already offer profitability reporting
008|Clinic cancellation refill and attendance desk|Healthcare administration|Morocco → Global|Morocco|Physiotherapy/dental groups; 3–15 practitioners; 500+ appointments/month|Cancellations and missed confirmations waste bookable capacity|8,8,7,9,7,8,6,5,8,9,9,7,6,5|S19;S20;S03;S04|Sensitive data even without clinical notes; bundled scheduling
009|Private-school fee reconciliation|Private school finance|Morocco → Africa|Morocco|Private schools; 300–1500 pupils; dedicated bursar|Cash, transfers and sibling payments fail to reconcile|8,8,7,10,6,9,7,5,7,8,9,6,7,4|S21;S22|Local competitors; annual sales windows; children data
010|Food-factory preventive-maintenance evidence|Manufacturing CMMS|Global|France|Food processors; 30–150 staff; 1–3 sites|Missed inspections and repairs create downtime and poor evidence|8,8,8,10,5,9,8,4,6,8,7,8,6,5|S23;S24|Excellent incumbents; implementation-heavy; no downtime guarantees
011|Property maintenance triage and contractor evidence|Property management|Morocco → Global|Morocco|Property managers; 200–1500 units; 5–30 staff|Repair requests lost between tenants and contractors|8,7,7,9,6,8,7,5,7,8,8,8,6,5|S09|Bundled property platforms and tenant support load
012|Riad group inquiry to deposit workflow|Hospitality and tourism|Morocco → Global|Morocco|Riad groups/DMCs; 3–15 properties or 10–50 staff|Slow multilingual group quotes and missing deposits lose business|8,7,6,8,7,7,6,5,8,8,9,8,6,6|S25|Seasonality; PMS and OTA integrations; avoid full PMS
013|MSP customer security-evidence collection|Cybersecurity compliance|Global|UK|MSPs; 10–100 staff; 20+ managed business clients|Repeated evidence gathering slows renewals and audits|8,8,8,9,5,8,9,4,5,7,5,9,6,7|S26|Security trust hurdle; Vanta/Drata and PSA incumbents
014|Multi-site purchase and AP approval desk|Procurement and accounts payable|Global|France|Distributors/service groups; 30–200 staff; 3+ sites|Unauthorized purchases and missing invoice approvals|8,8,8,9,5,8,8,4,6,8,7,8,5,7|S08;S15|ERP bundling; payment controls and implementation
015|Staffing timesheet-to-invoice reconciliation|Recruitment and staffing operations|Global|UK|Staffing agencies; 10–50 office staff; 100+ active placements|Unsigned timesheets delay billing and create disputes|8,8,8,9,6,8,8,5,6,9,6,8,6,6|S01|Payroll boundary and ATS bundling; worker-data security
016|Retail replenishment exceptions|Retail inventory|Morocco → Global|Morocco|Specialty retailers; 3–20 stores|Stockouts and overstock across stores|8,8,7,9,5,8,7,4,5,8,8,8,5,6|S08|Needs reliable stock data; POS bundling
017|Restaurant purchasing and recipe-cost variance|Restaurant operations|Morocco → Global|Morocco|Restaurant groups; 3–15 locations|Supplier price changes erode contribution margin|8,8,6,9,5,7,6,5,6,9,8,7,5,5|S08|Inventory discipline and low local WTP
018|SME leave and employee document workflow|HR|Morocco|Morocco|SMEs; 30–150 staff|Leave approvals and personnel files fragmented|8,6,5,8,5,8,5,3,8,6,8,5,4,4|S08|Payroll suites bundle it; weak incremental ROI
019|Moroccan payroll engine|Payroll|Morocco|Morocco|SMEs; 20–250 staff|Payroll errors and statutory updates|9,9,8,10,5,10,7,4,2,8,9,3,6,3|S02|REJECT initial build: compliance, liability, support; not 12-week safe MVP
020|COD return and settlement reconciliation|E-commerce operations|Morocco → Africa|Morocco|COD merchants; 1000+ orders/month|Courier settlements and return reasons mismatch|8,8,6,9,6,7,6,5,6,9,9,6,6,6|S11|Courier APIs and merchant churn; platform dependence
021|Generic SME CRM|CRM|Global|USA|SMEs; 5–100 staff|Untracked sales follow-ups|10,6,6,9,3,7,6,1,6,6,4,10,2,5|S08|REJECT: weak wedge against established CRM platforms
022|Generic lead database and outbound sequencer|Lead generation and sales automation|Global|USA|Sales teams; 5–50 reps|Prospecting time and weak pipeline|9,7,7,8,3,5,7,1,4,7,4,10,2,6|S26|REJECT: data access, deliverability, privacy and commoditization
023|SMB multi-touch advertising attribution|Advertising analytics|Global|USA|DTC advertisers spending $20000+/month|Conflicting attribution across channels|8,7,7,8,4,6,7,3,3,5,4,9,4,7|S26|Platform restrictions and unprovable attribution; downgrade
024|Generic AI customer-support agent|Customer support and AI agents|Global|USA|Online SMBs; 1000+ tickets/month|Repeated support questions|9,7,7,9,3,6,7,2,6,8,5,10,3,9|S27|REJECT generic: incumbents bundle AI; expensive failures
025|SMB customer-success health dashboard|Customer success|Global|USA|B2B SaaS; 10–100 staff|Churn signals fragmented|7,7,7,8,4,7,7,3,6,5,3,9,4,6|S27|Nice-to-have unless embedded in renewal workflow
026|General appointment scheduling|Scheduling and booking|Global|Global|Freelancers and microbusinesses|Calendar coordination|9,4,3,8,3,5,2,1,9,5,5,10,2,3|S20|REJECT: free/bundled substitutes and low ARPU
027|SME contract renewal obligations|Legal and contract management|Global|UK|SMEs; 50–250 staff; 100+ contracts|Missed renewals and obligation deadlines|7,7,7,8,4,8,7,4,6,7,5,8,5,7|S16|Legal review, confidentiality and infrequent engagement
028|Standalone compliant e-invoicing platform|Invoicing and accounting|Europe|France|VAT-registered SMEs|Mandated electronic invoice exchange|10,8,6,10,4,9,6,2,2,8,5,5,4,4|S28;S08|REJECT own regulated network; integrate approved platforms instead
029|Generic AI business-intelligence dashboard|BI and reporting|Global|USA|SMEs with spreadsheet reports|Manual reporting|8,5,5,8,3,5,5,1,6,5,4,10,2,8|S26|REJECT: poor differentiation versus BI and spreadsheets
030|Horizontal workflow automation platform|Workflow automation and iPaaS|Global|USA|SMEs integrating many tools|Repetitive cross-tool tasks|9,7,7,9,3,7,7,1,2,8,4,10,2,8|S26|REJECT: connector maintenance and incumbent ecosystems
031|Generic internal-tool builder|Internal tools|Global|USA|Technical SMBs|Slow back-office tool development|8,6,6,8,3,6,6,1,3,6,3,10,2,8|S26|REJECT: AI coding and incumbent platforms
032|Generic project management|Project management|Global|Global|Knowledge-work teams|Task coordination|10,5,5,9,2,6,5,1,7,5,4,10,2,4|S18|REJECT: ubiquitous free and bundled tools
033|CBAM supplier evidence collection|Trade and carbon compliance|Morocco → Europe|Morocco|Covered metal exporters supplying obligated EU importers|Emissions evidence requests threaten trade relationships|8,9,8,8,5,8,9,5,3,7,9,6,6,6|S29|Expert-dependent; scope/exemptions shrink SAM; longer compliant MVP
034|Auto workshop approval-to-job-card|Automotive repair|Morocco → Africa|Morocco|Independent garages; 5–25 technicians|Unapproved extras and poor parts/job tracking|8,7,6,9,6,8,5,5,7,9,9,7,6,4|S09|Local field onboarding and weak data discipline
035|Generic learning management platform|Education and LMS|Global|Global|Small training organizations|Course distribution and learner records|8,5,4,7,3,6,4,1,7,5,5,9,2,5|S21|REJECT: abundant free and mature alternatives
036|Localized employee cyber-awareness training|Cybersecurity training|Morocco → Africa|Morocco|Regulated SMEs; 50–500 employees|Phishing risk and staff training evidence|7,7,6,7,4,6,7,4,7,5,8,7,5,6|S26|Renewal engagement weak; simulated phishing consent concerns
037|General-purpose autonomous AI employee|AI automation and copilots|Global|USA|Unspecified SMB buyers|Broad admin work|8,5,5,5,2,3,5,1,5,3,4,10,1,10|S27|REJECT: unspecified buyer, reliability, churn and usage cost
038|Horizontal WhatsApp team inbox|Business communication|Morocco → Global|Morocco|SMBs; 3–20 sales agents|Shared-phone chaos|9,7,5,9,5,7,5,2,6,7,8,8,3,7|S04;S30|REJECT generic: platform dependence and many mature BSPs
039|Full dental practice management|Dental clinical software|Morocco|Morocco|Dental practices; 1–10 dentists|Scheduling, records and billing fragmentation|9,8,7,10,5,9,6,3,2,8,8,4,5,5|S19;S03|REJECT full suite: health-data regulation, migration and entrenched tools
040|SME vendor onboarding and document expiry|Procurement and document management|Global|GCC|Facility groups; 50–250 staff; 100+ vendors|Expired vendor documents block service and procurement|7,7,7,8,5,8,8,5,7,7,6,8,6,6|S16|Enterprise approval chains; document validity requires humans
'''
OPPS = []
for line in RAW.strip().splitlines():
    n,name,cat,market,country,icp,pain,scores,sources,risk = line.split('|')
    d = dict(zip(FACTORS,map(int,scores.split(','))))
    OPPS.append(dict(id='SAAS-'+n,name=name,cat=cat,market=market,country=country,icp=icp,pain=pain,f=d,sources=sources,risk=risk,score=round(sum(d[k]*w for k,w in zip(FACTORS,WEIGHTS))/10,1)))
OPPS.sort(key=lambda o:o['score'],reverse=True)
for rank,o in enumerate(OPPS,1): o['rank']=rank
BYID={o['id']:o for o in OPPS}
# Deep-dive shortlist: risk gates may outrank raw scores. Ranking table preserves numerical order.
DEEP=['SAAS-%03d'%i for i in range(1,11)]
TOP15=['SAAS-%03d'%i for i in range(1,16)]
SOURCES = [
('S01','French Ministry of Economy','https://presse.economie.gouv.fr/delais-de-paiement/','2025-07-11','VERIFIED / FACT','2024 average late payment 13.6 days; estimated EUR15bn SME/microenterprise cash impact. Not recoverable SaaS revenue or Moroccan data.'),
('S02','Sage Morocco','https://www.sage.com/fr-ma/blog/delais-de-paiement-a-quoi-faut-il-sattendre-en-2025/','2024-10-08','STRONG SIGNAL / secondary professional source','Law 69-21 phase includes MAD2m–10m turnover businesses in Jan 2025. Legal applicability must be confirmed; no automatic tax filing proposed.'),
('S03','CNDP','https://www.cndp.ma/notifier-une-demande-de-transfert-a-letranger/','Current page','VERIFIED / FACT','Cross-border personal-data transfers subject to statutory conditions; underlying treatment approval required for transfer authorization; stated 2-month review may extend once.'),
('S04','Meta WhatsApp policy','https://business.whatsapp.com/policy','Current page','VERIFIED / FACT','Opt-in and templates do not override prohibited verticals; debt collection explicitly listed. No WhatsApp collections in MVP.'),
('S05','OMPIC','http://www.ompic.ma/fr/actualites/office-marocain-de-la-propriete-industrielle-et-commerciale-les-creations-dentreprises','2025-09-01','STRONG SIGNAL / official indexed excerpt','56,572 business creations H1 2025; 17.7% growth. Not active-company count, serviceable market or paying SaaS demand.'),
('S06','Chaser pricing','https://www.chaserhq.com/chaser-pricing','Current page','VERIFIED / FACT','Rendered from-prices USD259/779/1169 monthly; annual toggle saves 10%, exact checkout billing-state needs confirmation. CSV and Odoo integrations already exist.'),
('S07','LeanPay','https://www.leanpay.io/tarifs','Current page','STRONG SIGNAL / official indexed price','Indexed starting EUR135 excl. tax/month; billing term not captured. Fetched features include multichannel reminders, disputes and email integration. Confirm quote.'),
('S08','Odoo','https://www.odoo.com/pricing','Current page','STRONG SIGNAL / official indexed excerpt','One App Free and broad ERP paid plans exist; geography/billing-specific live price DATA NOT VERIFIED. Generic invoicing/ERP wedge weak.'),
('S09','Jobber','https://www.getjobber.com/pricing/','Current page','VERIFIED / FACT','Core USD39 monthly or29 annual equivalent; Connect team169/129; Grow team349/249; Plus599/449. Selected payment and messaging features limited to US/Canada/UK.'),
('S10','Synchroteam','https://www.synchroteam.com/pricing.php','Current page','VERIFIED features; price UNKNOWN','Per-user monthly/annual model and free first admin with paid mobile worker; indexed price toggles ambiguous, exact prices not used.'),
('S11','Dashdoc','https://www.dashdoc.com/en','Current page','STRONG SIGNAL / official indexed excerpt','TMS includes dispatch, invoicing and tracking; official content lists POD/eCMR. Does not prove unmet demand.'),
('S12','Track-POD','https://www.track-pod.com/pricing-delivery-app/','Current page','VERIFIED / FACT','Advanced USD49 annual equivalent or59 monthly per driver, min3; task plan USD285 per1500 orders. Direct competition to generic POD.'),
('S13','Procore','https://www.procore.com/pricing','Current page','STRONG SIGNAL / official indexed excerpt','Custom pricing depends on products and construction volume. Numerical quotes UNKNOWN.'),
('S14','Knowify','https://knowify.com/knowify-vs-jobtread/','Current page','STRONG SIGNAL / official indexed excerpt','Core USD99 monthly equivalent annually or149 monthly; confirm pricing page before buying. Supports contract billing and jobs.'),
('S15','Conexiom','https://conexiom.com/blog/ai-order-automation','2026-06-16','STRONG SIGNAL / vendor-described capability','AI captures emailed orders and checks ERP data. Economic improvements are vendor claims, not assumed outcomes for new product.'),
('S16','Loopio','https://loopio.com/pricing/','Current page','STRONG SIGNAL / official indexed excerpt','Foundations tier includes10 seats. Current price UNKNOWN; do not repeat third-party USD20k quote as fact.'),
('S17','AutoRFP.ai','https://autorfp.ai/pricing','Current page','VERIFIED / FACT','USD899/month paid yearly for24 projects/year; USD1299 for50; unlimited users. Minimum12 months after30-day qualifying money-back period.'),
('S18','Productive','https://productive.io/pricing/','Current page','VERIFIED features; price UNKNOWN','Budgeting, time tracking, margin reporting, integrations and AI available. Crawled totals/toggles inconsistent; numeric price DATA NOT VERIFIED.'),
('S19','DabaDoc','https://www.dabadoc.com/ma','Current page','STRONG SIGNAL / official indexed excerpt','Moroccan booking and doctor agenda competitor. Clinician plan prices and free-plan scope UNKNOWN.'),
('S20','Cliniko','https://www.cliniko.com/pricing/','Current page','VERIFIED features; price UNKNOWN','30-day trial; annual billing gives one month free; optional SMS extra. Pricing grid not captured reliably; numeric plan price UNKNOWN.'),
('S21','Eduka','https://www.edukasoftware.com/pricing-and-plans/','Current page','VERIFIED features; indexed price conditional','Finance, family records and optional regional payments available; official index says Express free up to100 pupils, paid from EUR34. Finance module inclusion/quote must be confirmed.'),
('S22','E-Schools and Minassa','https://e-schools.ma/en','Current page','STRONG SIGNAL / official indexed excerpt','Local Moroccan school administration/billing competitors; E-Schools advertises Massar sync. Prices and actual customer satisfaction UNKNOWN. Minassa: https://minassa.ma/'),
('S23','MaintainX','https://www.getmaintainx.com/pricing','Current page','VERIFIED / FACT','Free Basic; Essential USD25 monthly/20 annual; Premium75/65 per user; advanced parts, API and AI already present. Vendor says average one-site implementation3 weeks.'),
('S24','Capterra MaintainX','https://www.capterra.com/p/179296/GetMaintainx/','Indexed 2026-09','STRONG SIGNAL / selected review summary','Indexed praise for mobile/photo updates and occasional connectivity complaints. Not a representative survey; no rating/count asserted.'),
('S25','Moroccan tourism ministry','https://mtaess.gov.ma/fr/tourisme-le-maroc-atteint-un-seuil-historique-de-pres-de-20-millions-de-touristes-en-2025/','2026-01-09','STRONG SIGNAL / official indexed release','19.8m tourist arrivals in2025, +14%. Macro demand, not SaaS budget or property count.'),
('S26','Research limitation','https://www.g2.com/','2026-09-15','UNKNOWN','Broad-category scan uses analyst knowledge of incumbents, not verified category growth or TAM. No paid search-volume, ad-library or SEO subscription data available.'),
('S27','ChartMogul','https://chartmogul.com/reports/saas-retention-the-ai-churn-wave/','2025-12-10','VERIFIED study results; sample-dependent','Approximately3500 companies; >=USD250k ARR subset; AI-native median GRR40% and NRR48%, B2B median NRR82%. Observational selected sample, not a forecast for these ideas.'),
('S28','French government e-invoicing','https://www.economie.gouv.fr/tout-savoir-sur-la-facturation-electronique-pour-les-entreprises','Current page','VERIFIED / FACT','Reception requirement Sept1 2026; SME/micro issuance Sept1 2027, scope-specific. Integrate approved platform; do not claim our overlay is one.'),
('S29','EU Commission CBAM','https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-definitive-regime_en','Current page','STRONG SIGNAL / official indexed excerpt','Definitive regime Jan1 2026; mass threshold50t and scope exclusions require checking by product/importer. Not all Moroccan exporters affected.'),
('S30','WhatsApp pricing','https://whatsappbusiness.com/products/platform-pricing/','Current page','STRONG SIGNAL / official indexed excerpt','Per-delivered-message pricing; country/category/BSP fees vary. No unlimited-message gross margin assumed.'),
('S31','G2 Chaser','https://www.g2.com/products/chaser/reviews?qs=pros-and-cons','Current index','STRONG SIGNAL / review summary','Indexed praise for reminders and cash-flow automation. Do not confuse AR Chaser with trychaser Slack task product.'),
('S32','ANRT','https://www.anrt.ma/sites/default/files/2025-10/Synth%C3%A8se-Brochure_Fr.pdf','2024–2025 survey','STRONG SIGNAL / official indexed source','Household TIC adoption context only. No inference that SME software budgets or card subscription willingness are high.'),
('S33','Stripe availability','https://stripe.com/global','Current page','UNKNOWN in this extraction','Country grid not captured reliably; secondary sources say Morocco unsupported. Confirm legal-entity eligibility with provider; no assumed native Stripe account.'),
('S34','Moroccan payment observatory','https://www.finances.gov.ma/fr/Pages/odp-publications.aspx','Current page','UNKNOWN underlying statistics','Publication landing page found but full text not retrieved. No numerical Moroccan overdue balance claimed.'),
('S35','Upflow product page','https://www.upflow.io/','Current page','VERIFIED vendor-described features','AR insights, collection agents, portal submission, cash matching and exception workflows already offered; page advertises free AR analytics. Vendor outcome percentages not treated as independent evidence.'),
('S36','LeanPay product page','https://www.leanpay.io/','Current page','VERIFIED vendor-described features','Dispute classification, disputed-invoice exclusion, action history, resolution on payment and accounting synchronization already offered. French + disputes is NOT a unique wedge. Testimonials not representative proof.'),
]
