"""Exact requested spreadsheet column structures; no hidden metadata columns."""
SCHEMAS={
'01_MASTER_RANKING':'''Opportunity ID|Rank|Opportunity|Category|Market|Primary Country|Target ICP|Core Problem|Demand /10|Pain /10|Willingness to Pay /10|Recurring Need /10|High-Ticket Potential /10|Advertising Ease /10|Sales Ease /10|Retention Potential /10|Competition /10|MVP Difficulty /10|AI Leverage /10|Global Potential /10|Morocco Potential /10|ROI Clarity /10|Differentiation /10|Overall Score /100|Opportunity Type|Recommendation''',
'02_GLOBAL_MARKETS':'''Opportunity ID|Rank|SaaS Category|Example Product|Target Customer|Market|Demand Signal|Growth Signal|Pain|WTP|Recurring Revenue|B2B Potential|High-Ticket Potential|Google Ads Potential|Meta Ads Potential|LinkedIn Potential|SEO Potential|Outbound Potential|Competition|Entry Difficulty|International Scalability|Overall Score|Why Attractive|Main Risk''',
'03_MOROCCO_MARKETS':'''Opportunity ID|Rank|Opportunity|Moroccan Industry|Target Customer|Company Size|Main Moroccan Problem|Current Solution|Localization Advantage|Arabic Need|French Need|Darija Opportunity|WhatsApp Opportunity|Local Payment Need|MAD Pricing Potential|Monthly WTP|High-Ticket Potential|Local Competition|International Competition|Advertising Potential|Sales Potential|Retention Potential|Market Size Signal|Overall Score''',
'04_MOROCCO_GLOBAL':'''Opportunity ID|Rank|Product|Initial Moroccan ICP|Morocco Advantage|Why Customers Buy|Expansion Market #1|Expansion Market #2|Expansion Market #3|Global ICP|Global Problem|Localization Required|International Competition|Morocco Price|International Price|Expansion Difficulty|Global Potential|Overall Score''',
'05_HIGH_TICKET':'''Opportunity ID|Rank|SaaS|Product Category|ICP|Decision Maker|Company Revenue|Problem Severity|Current Cost of Problem|Expected ROI|Monthly Price|Annual Contract Value|High-Ticket Score /10|Sales Cycle|Lead Acquisition Difficulty|Google Ads|LinkedIn|Cold Email|Direct Sales|Retention Potential|Switching Cost|Competition|Overall Score''',
'06_ADVERTISING':'''Opportunity ID|ICP|Google Search Demand|Commercial Intent|Google Ads Potential /10|Meta Ads Potential /10|LinkedIn Ads Potential /10|YouTube Ads Potential /10|Cold Email /10|LinkedIn Outreach /10|WhatsApp /10|SEO /10|Referral /10|Partnerships /10|Best Channel|CAC Range|Why Advertising Should Work|Main Advertising Risk''',
'07_CUSTOMER_PROFILE':'''Opportunity ID|ICP|Industry|Company Size|Geography|Decision Maker|Buyer Role|Employee Count|Revenue Range|Main Pain|Pain Frequency|Current Workflow|Current Software|Current Cost|Desired Outcome|Purchase Trigger|Main Objection|Willingness to Pay|Where They Search|Where They Spend Time|Best Acquisition Channel''',
'08_COMPETITORS':'''Opportunity ID|Competitor|Website|Country|Target Customer|Pricing|Free Plan|Core Features|AI Features|Main Strength|Main Weakness|Reviews / Sentiment|Market Position|Advertising Presence|SEO Strength|Why Customers Choose Them|Our Differentiation|Threat Level /10''',
'09_PRODUCT':'''Opportunity ID|Product Name|One-Line Value Proposition|ICP|Core Problem|Core Solution|Core Workflow|MVP Feature #1|MVP Feature #2|MVP Feature #3|MVP Feature #4|MVP Feature #5|AI Feature|Automation|Integrations|Dashboard|Reporting|Notifications|User Roles|Mobile Needed|Web Needed|API Needed|Technical Complexity /10|Time to MVP''',
'10_PRICING_UNIT_ECONOMICS':'''Opportunity ID|Market|Plan|Monthly Price|Annual Price|Target Customer|Expected ARPU|Gross Margin %|Estimated CAC|Monthly Churn %|Estimated LTV|LTV:CAC|Payback Months|Customers for $10k MRR|Customers for $50k MRR|Customers for $100k MRR|Confidence Level|Assumptions''',
'11_VALIDATION':'''Opportunity ID|ICP|Hypothesis|Landing Page Ready|Outbound List Size|Emails Sent|Replies|Demos|Trials|Paid Pilots|Customers|Revenue|Conversion Rate|CAC Signal|Strongest Objection|Strongest Buying Signal|Validation Score|Decision|Reason''',
'12_FIRST_100_CUSTOMERS':'''Opportunity ID|Stage|Customer Range|Strategy|Channel|Target ICP|Offer|Expected Leads|Expected Conversion|Expected Customers|Estimated CAC|Estimated Revenue|Time Required|Key Action''',
'13_FINANCIAL_MODEL':'''Opportunity ID|Scenario|Month|Customers|New Customers|Churned Customers|ARPU|MRR|ARR|CAC|Acquisition Cost|Product Costs|Team Costs|Marketing Costs|Other Costs|Total Costs|Gross Profit|Net Profit''',
'14_RISK_ANALYSIS':'''Opportunity ID|Opportunity|Market Risk|Product Risk|Competition Risk|CAC Risk|Retention Risk|Technical Risk|Regulatory Risk|Platform Dependency|Localization Risk|Cash Flow Risk|Founder Dependency|Overall Risk /10|Mitigation''',
'15_FINAL_DECISION':'''Opportunity ID|Rank|Opportunity|Market|ICP|Monthly Price|High-Ticket Potential|Demand|Pain|WTP|CAC Potential|Advertising|Sales Difficulty|Retention|MVP Speed|Competition|Moat|Morocco Advantage|Global Potential|AI Advantage|ROI Clarity|Risk|Final Score /100|Build Priority|Final Verdict''',
}
SCHEMAS={k:v.split('|') for k,v in SCHEMAS.items()}
