"""Proposed ICPs, channels and prices: all HYPOTHESES / ASSUMPTIONS unless sourced."""
# Fields: id,name,buyer,revenueUSD,workflow,features,AI,integrations,demo,trigger,objection,firstChannel,keyword,MADpro,EURpro,USDpro,weeks,complexities,cacLow,cacHigh,churnLow,churnHigh,marginLow,marginHigh,currentMonthlyCostUSD,advanced
RAW='''
001|Encaisse Desk|Owner/CFO; accountant champion|1m–15m|Import aged receivables → validate balances → assign exception → request missing document → record promise → reconcile cleared payment|Validated CSV imports;Aging and missing-document queue;Owner-assigned disputes;Approved email follow-ups and call tasks;Payment reconciliation and audit export|Classify reply/dispute reasons with confidence and human approval|CSV first; one Sage export format; Microsoft365/Gmail later; Odoo after demand|Upload30 redacted overdue invoices; show balances lacking evidence and next actions in10min; cash impact needs30–60days|Overdraft pressure; month-end backlog; lost collector|Our ERP already does reminders|Accountant referrals + founder outbound|logiciel suivi créances grossiste; relance facture impayée|2500|299|349|6–8|5,3,6,5,5,5,5|400|1400|1|2.5|75|85|300–2000 of attributable admin/rework; excludes invoice principal|Multi-entity reporting; accountant portal; dispute taxonomy
002|Intervention Cash|Owner/operations manager; dispatcher champion|0.5m–8m|Book recurring job → technician checklist → photos/signature → office approval → invoice-ready pack|Customer/site register;Recurring visit scheduler;Mobile checklist;Photo/signature evidence;Invoice-ready export|Convert technician notes into draft service report; no safety certification|CSV; email; calendar; one accounting export|Complete one sample job on phone; signed report and invoice-ready pack appear in10min|Service-contract renewal; overdue unbilled jobs|Technicians will not use another app|HVAC supplier partnerships|logiciel intervention maintenance climatisation|2000|249|299|8–10|6,3,5,4,6,7,6|500|1800|1|2.5|70|85|400–2500 admin/revisits|Offline sync; renewal scheduling; customer portal
003|POD Close|Carrier owner/CFO; billing supervisor|1m–20m|Upload POD → match shipment → flag missing proof → resolve discrepancy → export billable load|Shipment CSV;Mobile POD upload;Shipment-document matching;Exception queue;Invoice-ready packet|Extract load references and flag illegible PODs for review|TMS CSV first; driver upload; accounting export; one TMS API later|Match10 sample deliveries; identify delivered-but-unbillable loads in10min|Billing backlog; large shipper rejects invoices|Our TMS can do this|Transport-accountant/TMS partners|proof of delivery invoicing software; facture transport CMR|3500|499|599|8–12|6,5,7,5,6,6,7|900|3000|0.8|2|70|85|600–4000 admin and dispute handling|Shipper-specific evidence rules; billing SLA analytics
004|Variation Proof|Managing director/commercial director; quantity surveyor|2m–30m|Record extra work → attach evidence → request approval → track status → export claim pack|Project register;Mobile change log;Photo/time evidence;Approval link;Variation billing export|Draft variation narrative citing original evidence; human signs|CSV; email; document storage; accounting export|Turn one unapproved variation into an approval-ready pack in10min; recovery not proven|Margin surprise; rejected final account|GC will refuse another portal or extra charge|Trade-association outbound|construction change order software subcontractor|3500|499|599|6–10|5,4,5,6,5,6,6|800|3000|1|2.5|75|88|800–6000 admin and unrecovered contribution risk|Contract template library; approval escalation; multi-project margin
005|Order Intake Desk|COO/head of customer service; ERP manager|3m–40m|Forward PO → extract → match customer SKU/unit → human review → ERP draft order|PO inbox;PDF table extraction;SKU alias dictionary;Confidence-based review;Validated CSV export|Document extraction and SKU matching; never auto-send low-confidence orders|One ERP CSV; shared inbox; Odoo/Sage connector later|Process10 redacted POs against SKU list; measure corrected minutes/order and unit errors|Order growth without hiring; frequent credit notes|One wrong unit or price can erase savings|ERP implementer partnerships|sales order automation distributor PDF to ERP|6000|799|999|10–12|7,7,8,4,7,7,8|1500|5000|0.7|2|60|80|1200–7000 labor/rework; local labor may make ROI insufficient|Customer-specific dictionaries; ERP read-only validation; exception analytics
006|Bid Evidence|Bid director/sales director; proposal manager|2m–30m|Import approved answers → upload tender → map requirements → draft cited response → approve → export|Approved answer library;Tender import;Requirement checklist;Cited drafts;Word export and approvals|Retrieval with citations, stale-answer flags, abstention|DOCX/XLSX/PDF first; SharePoint later|Answer10 questions with sources; show unknowns instead of invented credentials|2+ bids/month; missed deadline; bid-manager vacancy|ChatGPT/Loopio already does this|Bid-consultant referrals + targeted email|logiciel réponse appel offres mémoire technique|4500|599|799|6–10|6,7,5,6,5,5,6|1000|4000|1|3|65|85|1000–8000 proposal labor|Clause owners; expiry dates; multilingual response library
007|Margin Guard|Agency founder/COO; account director|0.7m–8m|Import budgets/time → compare scope → flag retainer overrun → approve change → review margin|Retainer budgets;Time CSV import;Scope exception queue;Margin dashboard;Client-change approval|Classify request as possible out-of-scope with rationale|Harvest/Toggl CSV; project export; Slack later|Import last-month time and budgets; identify3 over-serviced retainers in10min|Agency growth but cash/profit flat|Team will not log time; Productive already reports it|Agency consultants + founder outbound|agency retainer profitability software|1800|199|249|4–6|4,4,5,3,4,4,4|300|1200|1.5|4|80|90|300–2500 reporting/scope labor|Scope agreement comparison; resource forecast; client approval
008|Slot Refill|Clinic owner/practice manager; reception lead|0.4m–5m|Import appointments → confirm consent → confirm/cancel → invite waitlist → track attended slots|Appointment CSV/calendar;Consent/preferences;Confirmation links;Waitlist workflow;Attendance audit|Suggest waitlist ordering by explicit availability, not health inference|Calendar/CSV; SMS provider; approved messaging only|Cancel one test slot and refill with a consenting test contact in10min; attendance ROI needs4weeks|Documented cancellation rate and idle paid capacity|Existing booking tool already sends reminders|Practice consultants + targeted local demos|logiciel rappel rendez vous cabinet médical|1500|199|249|6–8|5,3,6,8,6,7,6|350|1500|1.5|3.5|65|82|200–1800 attributable lost contribution/admin|Multi-location waitlist; demand-time analytics; audit exports
009|Frais Clairs|School owner/finance director; bursar|0.5m–8m|Import fee schedule → match family receipts → review exceptions → issue receipt → statement|Family fee ledger;Bank CSV matching;Cash receipt audit;Sibling allocation;Parent statement export|Suggest transfer-to-family matches; human confirmation|Bank CSV; school roster CSV; no assumed Massar API|Match20 anonymized receipts and surface duplicates/unmatched families in10min|New school year; unexplained family balances|Our school suite already does finance|School-accountant partnerships|logiciel paiement frais scolarité Maroc|2500|349|399|8–10|5,4,6,7,6,7,6|600|2400|0.5|1.5|65|82|300–2000 reconciliation/admin|Multi-campus controls; local licensed PSP; accountant dashboard
010|Maintenance Evidence|Plant manager/maintenance head; quality manager|3m–40m|Register critical assets → scheduled check → report issue → work order → review evidence|Asset register;Recurring checklist;Mobile work orders;Photo evidence;Overdue maintenance report|Draft SOP from approved manual; reviewer verifies|CSV assets; QR labels; no IoT in MVP|Run one asset inspection and generate an exception/action report in10min; avoided downtime not immediately demonstrable|Audit findings; recurring missed maintenance|MaintainX/Fiix already works well|Industrial maintenance consultants|logiciel GMAO agroalimentaire PME|4500|599|699|8–12|6,4,6,6,7,7,7|1200|4000|0.7|2|70|85|800–5000 admin/rework; excludes speculative downtime loss|Spare parts; site comparisons; ERP interface
011|Repair Desk|Property management director|0.5m–10m|Tenant request → triage → assign vendor → proof → owner approval|Request form;Unit register;Vendor assignment;Completion proof;Owner cost report|Categorize request with human safety escalation|Email; unit CSV; contractor portal|Log leak; assign; generate owner approval in10min|Portfolio doubles; repeat unresolved repairs|Tenant support will be burdensome|Property-accountant referrals|property maintenance work order software|2000|299|349|6–8|5,4,5,5,6,7,5|600|2000|1|3|70|85|300–2500 coordination|Supplier SLA; resident portal; recurring maintenance
012|Riad Quote|DMC/riad-group owner; reservations lead|0.5m–10m|Inquiry → availability check → group quote → deposit instruction → follow-up|Shared inquiry queue;Quote templates;Manual availability;Deposit status;Conversion report|Translate and draft factual quote from approved inventory|Email; CSV rates; PMS export later; no OTA scraping|Create a bilingual group quote from sample request in10min|High-season inquiry backlog|PMS already handles it; seasonal budget|Tourism-association partnerships|logiciel devis groupe riad agence réceptive|1800|249|299|4–8|4,5,6,4,6,6,5|350|1500|2|5|70|85|250–2000 quote labor/lost contribution|Room-block approvals; itinerary builder; PMS connector
013|MSP Evidence|MSP owner/security lead|1m–20m|Map evidence requests → assign client → upload → expiry review → export audit pack|Client register;Evidence checklist;Owner task queue;Expiry alerts;Audit pack export|Classify docs and cite evidence; no compliance certification|M365; PSA CSV; read-only integration later|Show missing evidence for one sample client in10min|Renewal/audit due; staff shortage|Entrusting sensitive evidence to a startup|MSP peer communities + consultant partners|MSP compliance evidence management|5500|699|899|10–12|7,5,8,7,6,6,8|1500|5000|0.8|2|70|85|1000–6000 evidence labor|Tenant-isolated connector jobs; policy templates; security review
014|Approval Desk|CFO/procurement manager|3m–40m|Request → approval → PO → invoice match → exceptions|Spend requests;Approval routing;PO register;Invoice matching;Audit export|Extract invoice lines and flag discrepancies|CSV; email; one ERP export; no money movement|Route sample purchase and flag duplicate invoice in10min|Unauthorized spend; growth to3+ sites|ERP already covers approvals|ERP/accounting partners|purchase approval software multi site SME|4500|599|749|8–12|6,5,7,6,6,6,7|1000|4000|1|2.5|70|85|700–4500 finance admin/errors|Delegated limits; budget checks; vendor risk docs
015|Timesheet Close|Staffing agency owner/CFO; payroll manager|3m–30m|Import placements → collect timesheets → client approval → reconcile → billing export|Placement CSV;Timesheet capture;Client approvals;Rate mismatch flags;Invoice-ready export|Read signed sheets; flag inconsistent hours|ATS CSV; timesheet uploads; payroll export only|Approve one sample timesheet and catch rate mismatch in10min|Payroll paid before client billed|Must integrate ATS and payroll perfectly|Staffing-accountant referrals|staffing timesheet invoice reconciliation software|3500|499|599|8–10|6,5,7,6,6,6,7|900|3500|1|2.5|72|86|700–5000 reconciliation and disputes|Multi-client rate cards; credit notes; audit controls
'''
KEYS=['n','product','buyer','rev','workflow','features','ai','integrations','demo','trigger','objection','channel','keyword','mad','eur','usd','weeks','complex','caclo','cachi','churnlo','churnhi','gmlo','gmhi','cost','advanced']
PROFILES={}
for row in RAW.strip().splitlines():
    p=dict(zip(KEYS,row.split('|')))
    assert len(row.split('|'))==len(KEYS)
    for k in ['mad','eur','usd','caclo','cachi','churnlo','churnhi','gmlo','gmhi']: p[k]=float(p[k])
    p['features']=p['features'].split(';'); p['complex']=list(map(int,p['complex'].split(',')))
    PROFILES['SAAS-'+p['n']]=p
# Google, Meta, LinkedIn ads, YouTube, email, LinkedIn outreach, WhatsApp, SEO, referral, partnership
CHANNELS={
'001':[7,3,4,3,8,7,2,7,9,9], '002':[8,6,3,4,7,6,7,7,9,9],
'003':[6,3,5,3,8,7,6,6,8,9], '004':[8,5,5,4,8,7,6,8,8,8],
'005':[6,2,6,3,8,8,5,6,8,9], '006':[7,2,6,4,8,8,3,7,8,9],
'007':[7,5,4,4,8,8,4,7,9,9], '008':[8,7,2,3,6,4,7,7,9,8],
'009':[6,5,3,3,6,5,5,6,9,9], '010':[6,2,5,3,7,7,5,6,8,9],
'011':[7,5,4,3,7,7,6,7,8,8], '012':[7,7,3,4,7,6,8,7,9,9],
'013':[6,2,6,3,8,8,3,7,8,9], '014':[6,2,5,3,7,7,3,6,8,9],
'015':[6,3,5,3,8,8,4,6,8,9]}
# Competitor rows are an identified comparison set, not claims that every product has been tested.
# name, website, origin (general knowledge, not verified headquarters), positioning, verified price/source
COMPETITORS={
'001': [('Chaser','chaserhq.com','UK','AR reminders, integrations and forecasts','From USD259/mo shown; billing toggle confirm [S06]'),('Upflow','upflow.io','France/USA','AR and payments; modern finance teams','DATA NOT VERIFIED; pricing page legal terms only'),('LeanPay','leanpay.io','France','French-language AR, disputes and multichannel','Indexed from EUR135 excl.tax/mo; term confirm [S07]'),('Esker','esker.com','France','Enterprise order-to-cash/document automation','DATA NOT VERIFIED; request quote'),('Odoo','odoo.com','Belgium','ERP with invoice follow-up and accounting','Geographic paid plans; One App Free conditions [S08]')],
'002': [('Jobber','getjobber.com','Canada','SMB home-service suite','Core USD39 monthly/29 annual equivalent [S09]'),('Synchroteam','synchroteam.com','France','Multilingual field-service operations','Per-user; exact amount DATA NOT VERIFIED [S10]'),('Praxedo','praxedo.com','France','Field-service scheduling and mobile execution','DATA NOT VERIFIED'),('Organilog','organilog.com','France','French field-service and intervention management','DATA NOT VERIFIED'),('ServiceM8','servicem8.com','Australia','Small contractor job workflow','DATA NOT VERIFIED')],
'003': [('Dashdoc','dashdoc.com','France','TMS; dispatch to invoicing','DATA NOT VERIFIED [S11]'),('Truckbase','truckbase.com','USA','Small carrier dispatch and back office','DATA NOT VERIFIED'),('Rose Rocket','roserocket.com','Canada','Carrier/broker transport management','DATA NOT VERIFIED'),('Track-POD','track-pod.com','DATA NOT VERIFIED','Route execution and POD','USD59 monthly/49 annual per driver min3 [S12]'),('Onfleet','onfleet.com','USA','Last-mile delivery orchestration; adjacent','DATA NOT VERIFIED')],
'004': [('Procore','procore.com','USA','Broad construction suite','Custom quote by products/volume [S13]'),('Autodesk Construction','construction.autodesk.com','USA','Construction cost/document platform','DATA NOT VERIFIED'),('Buildertrend','buildertrend.com','USA','Builder management suite','DATA NOT VERIFIED'),('Planyard','planyard.com','Estonia','Construction budgets and cost control','DATA NOT VERIFIED'),('Knowify','knowify.com','USA','Trade contractor jobs and contract billing','Indexed USD149 monthly/99 annual equivalent [S14]')],
'005': [('Conexiom','conexiom.com','Canada','ERP order automation','DATA NOT VERIFIED [S15]'),('Esker','esker.com','France','Order entry and enterprise document AI','DATA NOT VERIFIED'),('OrderEase','orderease.com','Canada','Wholesale order ecosystem','DATA NOT VERIFIED'),('Pepper','usepepper.com','USA','Food distributor ordering; adjacent','DATA NOT VERIFIED'),('Odoo','odoo.com','Belgium','ERP-native sales and inventory','Geographic plans; One App Free conditions [S08]')],
'006': [('Loopio','loopio.com','Canada','RFP response library and collaboration','10-seat Foundations; price UNKNOWN [S16]'),('Responsive','responsive.io','USA','Response management','DATA NOT VERIFIED'),('AutoRFP.ai','autorfp.ai','Australia','AI response automation','USD899/mo paid yearly;24 projects/year [S17]'),('Inventive AI','inventive.ai','USA','AI RFP responses','DATA NOT VERIFIED'),('SiftHub','sifthub.io','DATA NOT VERIFIED','AI sales/response knowledge','DATA NOT VERIFIED')],
'007': [('Productive','productive.io','Croatia','Agency budgets, resources and margins','DATA NOT VERIFIED: crawler pricing inconsistent [S18]'),('Scoro','scoro.com','Estonia','Professional service work management','DATA NOT VERIFIED'),('Teamwork','teamwork.com','Ireland','Client project and time management','DATA NOT VERIFIED'),('Accelo','accelo.com','USA/Australia','Professional services automation','DATA NOT VERIFIED'),('Harvest','getharvest.com','USA','Time and invoicing; lower-cost adjacent','DATA NOT VERIFIED')],
'008': [('DabaDoc','dabadoc.com','Morocco','Local doctor bookings and agenda','Professional fees UNKNOWN [S19]'),('Cliniko','cliniko.com','Australia','Allied-health practice management','Numeric grid UNKNOWN;30-day trial [S20]'),('Doctolib','doctolib.fr','France','Health booking and practice management','DATA NOT VERIFIED'),('SimplyBook.me','simplybook.me','DATA NOT VERIFIED','General booking platform; adjacent','DATA NOT VERIFIED'),('Jane','jane.app','Canada','Clinic booking, billing and notes','DATA NOT VERIFIED')],
'009': [('Eduka','edukasoftware.com','DATA NOT VERIFIED','International/francophone school suite','Indexed from EUR34; finance scope confirm [S21]'),('E-Schools','e-schools.ma','Morocco','Local school suite and billing','DATA NOT VERIFIED [S22]'),('Minassa','minassa.ma','Morocco','Moroccan school administration/payments','DATA NOT VERIFIED [S22]'),('Classter','classter.com','Greece','School/student information suite','DATA NOT VERIFIED'),('Fedena','fedena.com','India','School ERP','DATA NOT VERIFIED')],
'010': [('MaintainX','getmaintainx.com','USA','Mobile maintenance/work orders','Essential USD25 monthly/20 annual per user [S23]'),('UpKeep','upkeep.com','USA','Mobile CMMS','DATA NOT VERIFIED'),('Limble','limblecmms.com','USA','Maintenance and assets','DATA NOT VERIFIED'),('Fiix','fiixsoftware.com','Canada','CMMS and asset intelligence','DATA NOT VERIFIED'),('Mobility Work','mobility-work.com','France','Maintenance-management platform','DATA NOT VERIFIED')]
}
